In [1]:
import pandas as pd
import sqlite3

In [2]:
orders = pd.read_csv("orders - orders.csv")

orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [4]:
orders.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name'],
      dtype='object')

In [5]:
orders.columns = orders.columns.str.strip().str.lower()
orders.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name'],
      dtype='object')

In [6]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [7]:
conn = sqlite3.connect("restaurants.db")

with open("restaurants.sql", "r") as file:
    sql_script = file.read()

conn.executescript(sql_script)

In [8]:
restaurants = pd.read_sql("SELECT * FROM restaurants", conn)

restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [11]:
users = pd.read_json("users.json")
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [12]:
type(users)

pandas.core.frame.DataFrame

In [13]:
merged_df = orders.merge(
    users,
    on="user_id",
    how="left"
)

In [14]:
final_df = merged_df.merge(
    restaurants,
    on="restaurant_id",
    how="left"
)

final_df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,2023-02-18,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,2023-01-18,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,2023-07-15,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,2023-10-04,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,2023-12-25,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [15]:
final_df.to_csv("final_food_delivery_dataset.csv", index=False)

In [16]:
final_df[final_df['membership'] == 'Gold'] \
    .groupby('city')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

city
Chennai      1080909.79
Pune         1003012.32
Bangalore     994702.59
Hyderabad     896740.19
Name: total_amount, dtype: float64

In [17]:
final_df.groupby('cuisine')['total_amount'] \
    .mean() \
    .sort_values(ascending=False)

cuisine
Mexican    808.021344
Italian    799.448578
Indian     798.466011
Chinese    798.389020
Name: total_amount, dtype: float64

In [18]:
user_total = final_df.groupby('user_id')['total_amount'].sum()

(user_total > 1000).sum()

np.int64(2544)

In [19]:
bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ['3.0–3.5', '3.6–4.0', '4.1–4.5', '4.6–5.0']

final_df['rating_range'] = pd.cut(final_df['rating'], bins=bins, labels=labels)

final_df.groupby('rating_range')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

C:\Users\santh\AppData\Local\Temp\ipykernel_2200\3208765811.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  final_df.groupby('rating_range')['total_amount'] \

rating_range
4.6–5.0    2197030.75
4.1–4.5    1960326.26
3.0–3.5    1881754.57
3.6–4.0    1717494.41
Name: total_amount, dtype: float64

In [20]:
final_df[final_df['membership'] == 'Gold'] \
    .groupby('city')['total_amount'] \
    .mean() \
    .sort_values(ascending=False)

city
Chennai      808.459080
Hyderabad    806.421034
Bangalore    793.223756
Pune         781.162243
Name: total_amount, dtype: float64

In [21]:
restaurant_count = final_df.groupby('cuisine')['restaurant_id'].nunique()
revenue = final_df.groupby('cuisine')['total_amount'].sum()

pd.DataFrame({
    "restaurant_count": restaurant_count,
    "total_revenue": revenue
}).sort_values(by=['restaurant_count', 'total_revenue'], ascending=[True, False])

         restaurant_count  total_revenue
cuisine
Chinese               120     1930504.65
Italian               126     2024203.80
Indian                126     1971412.58
Mexican               128     2085503.09

In [22]:
gold_orders = final_df[final_df['membership'] == 'Gold'].shape[0]
total_orders = final_df.shape[0]

round((gold_orders / total_orders) * 100)

50

In [24]:
restaurant_stats = final_df.groupby('restaurant_name_x').agg(
    avg_order_value=('total_amount', 'mean'),
    total_orders=('order_id', 'count')
)

restaurant_stats[restaurant_stats['total_orders'] < 20] \
    .sort_values(by='avg_order_value', ascending=False)

                                   avg_order_value  total_orders
restaurant_name_x
Hotel Dhaba Multicuisine               1040.222308            13
Sri Mess Punjabi                       1029.180833            12
Ruchi Biryani Punjabi                  1002.140625            16
Sri Delights Pure Veg                   989.467222            18
Classic Kitchen Family Restaurant       973.167895            19
...                                            ...           ...
Annapurna Tiffins Punjabi               621.828947            19
Darbar Tiffins Non-Veg                  596.815556            18
Darbar Restaurant Punjabi               589.972857            14
Spice Tiffins Pure Veg                  578.578667            15
Ruchi Mess Punjabi                      572.686471            17

[170 rows x 2 columns]

In [25]:
final_df.groupby(['membership', 'cuisine'])['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

membership  cuisine
Regular     Mexican    1072943.30
            Italian    1018424.75
Gold        Mexican    1012559.79
            Italian    1005779.05
Regular     Indian      992100.27
Gold        Indian      979312.31
            Chinese     977713.74
Regular     Chinese     952790.91
Name: total_amount, dtype: float64

In [26]:
final_df['quarter'] = final_df['order_date'].dt.to_period('Q')

final_df.groupby('quarter')['total_amount'] \
    .sum() \
    .sort_values(ascending=False)

quarter
2023Q3    2037385.10
2023Q4    2018263.66
2023Q1    1993425.14
2023Q2    1945348.72
2024Q1      17201.50
Freq: Q-DEC, Name: total_amount, dtype: float64

In [27]:
gold_orders_count = final_df[final_df['membership'] == 'Gold'].shape[0]
gold_orders_count

4987

In [28]:
hyderabad_revenue = final_df[final_df['city'] == 'Hyderabad']['total_amount'].sum()

round(hyderabad_revenue)

1889367

In [29]:
final_df['user_id'].nunique()

2883

In [30]:
gold_avg_order_value = final_df[final_df['membership'] == 'Gold']['total_amount'].mean()

round(gold_avg_order_value, 2)

np.float64(797.15)

In [31]:
top_gold_city = (
    final_df[final_df['membership'] == 'Gold']
    .groupby('city')['total_amount']
    .sum()
    .idxmax()
)

top_gold_city

'Chennai'

In [34]:
orders_in_top_gold_city = final_df[
    (final_df['membership'] == 'Gold') &
    (final_df['city'] == top_gold_city)
].shape[0]

orders_in_top_gold_city

1337

In [35]:
high_rating_orders = final_df[final_df['rating'] >= 4.5].shape[0]
high_rating_orders

3374

In [36]:
orders.merge(users, on="user_id", how="left")

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name,name,city,membership
0,1,2508,450,2023-02-18,842.97,New Foods Chinese,User_2508,Hyderabad,Regular
1,2,2693,309,2023-01-18,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular
2,3,2084,107,2023-07-15,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold
3,4,319,224,2023-10-04,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold
4,5,1064,293,2023-12-25,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular
...,...,...,...,...,...,...,...,...,...
9995,9996,2528,249,2023-05-21,1211.96,Royal Kitchen North Indian,User_2528,Hyderabad,Gold
9996,9997,2867,267,2023-08-06,1188.05,Darbar Cafe Punjabi,User_2867,Bangalore,Regular
9997,9998,522,420,2023-11-11,979.44,Ruchi Tiffins Chinese,User_522,Bangalore,Gold
9998,9999,319,492,2023-09-08,1105.93,Swagath Kitchen North Indian,User_319,Bangalore,Gold
9999,10000,457,439,2023-10-21,879.58,Classic Cafe Family Restaurant,User_457,Chennai,Regular

In [37]:
final_df.shape[0]

10000

In [38]:
final_df.isna().sum()

order_id               0
user_id                0
restaurant_id          0
order_date             0
total_amount           0
restaurant_name_x      0
name                   0
city                   0
membership             0
restaurant_name_y      0
cuisine                0
rating                 0
rating_range         331
quarter                0
dtype: int64

In [39]:
final_df = merged_df.merge(restaurants, on="restaurant_id", how="left")